language: rust
sudo: enabled
services:
  - docker
rust:
  - stable
before_install:
  - docker run -d -p 3000:3000 juxt/crux-standalone:20.07-1.10.0
script:
    - cargo build
    - cargo test --examples
    - cargo test --examples --features "async"